### ISSUE TITLE
crash when importing entries containing the character '»'

### ISSUE THREAD

**Issue by stesix** [anaynayak/buildnotify#109]
Using the cctray-xml-ccxml-plugin (https://github.com/jenkinsci/cctray-xml-plugin/blob/master/README.md#cctray-xml-ccxml-plugin) for Jenkins in conjunction with multi-branch jobs crashes the buildnotify while importing the entries the first time.

```
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/buildnotifylib/preferences.py", line 65, in configure_projects
  File "build/bdist.linux-x86_64/egg/buildnotifylib/server_configuration_dialog.py", line 110, in open
  File "build/bdist.linux-x86_64/egg/buildnotifylib/server_configuration_dialog.py", line 103, in get_server_config
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbb' in position 17: ordinal not in range(128)
Aborted (core dumped)
```

The character in question is '»'.

**Comment by anaynayak** [comment]
Closing this given the corresponding fix has been merged.
