### ISSUE TITLE
Crash on start on Arch Linux

### ISSUE THREAD

**Issue by Deuchnord** [anaynayak/buildnotify#112]
With a fresh install of BuildNotify on my Arch system ([from the AUR](https://aur.archlinux.org/packages/buildnotify)), the app crashes immediately on start with the following trace:

```
Traceback (most recent call last):
  File "/bin/buildnotifyapplet.py", line 2, in <module>
    import buildnotifylib
  File "/usr/lib/python2.7/site-packages/buildnotifylib/__init__.py", line 1, in <module>
    from buildnotifylib.buildnotify import BuildNotify   # NOQA
  File "/usr/lib/python2.7/site-packages/buildnotifylib/buildnotify.py", line 6, in <module>
    from buildnotifylib.app_ui import AppUi
  File "/usr/lib/python2.7/site-packages/buildnotifylib/app_ui.py", line 6, in <module>
    from buildnotifylib.app_menu import AppMenu
  File "/usr/lib/python2.7/site-packages/buildnotifylib/app_menu.py", line 8, in <module>
    from buildnotifylib.preferences import PreferencesDialog
  File "/usr/lib/python2.7/site-packages/buildnotifylib/preferences.py", line 5, in <module>
    from buildnotifylib.server_configuration_dialog import ServerConfigurationDialog
  File "/usr/lib/python2.7/site-packages/buildnotifylib/server_configuration_dialog.py", line 6, in <module>
    from buildnotifylib.config import Config
  File "/usr/lib/python2.7/site-packages/buildnotifylib/config.py", line 3, in <module>
    from buildnotifylib.core.keystore import Keystore
  File "/usr/lib/python2.7/site-packages/buildnotifylib/core/keystore.py", line 1, in <module>
    import keyring
ImportError: No module named keyring
```

**Comment by anaynayak** [comment]
@Deuchnord thanks for raising this. It seems the source on Arch is quite old. I'm not sure whats the exact process to roll that out. This issue shouldn't happen via master.

**Comment by Deuchnord** [comment]
I see.

Have you plan to release a new version, so we can make profit of the last changes? :)

**Comment by anaynayak** [comment]
I'm not sure whom to contact to get new versions rolled out for Arch linux. 
The alternative that I've been thinking about is to instead see if rolling out snap files is better. sadly I haven't been able to spend enough time doing that.

Have some time now, Will try and get it working against python 3 as well (which will simplify a lot of the setup and installation).

**Comment by Deuchnord** [comment]
Package has been updated on AUR and is now functional :+1:
