### ISSUE TITLE
buildnotify dies if network is not available

### ISSUE THREAD

**Issue by Bu11etmagnet** [anaynayak/buildnotify#38]
Every time my machine goes through a susped/resume, BuildNotify dies:
```
$ tail -15 /tmp/buildnotify.log 
processed http://hudson.internal:8080/cc.xml
checking http://hudson.internal:8080/cc.xml
<urlopen error [Errno -3] Temporary failure in name resolution>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/buildnotifylib/buildnotify.py", line 45, in update_projects
    self.app_notification.update_projects(integration_status)
  File "/usr/local/lib/python2.7/dist-packages/buildnotifylib/app_notification.py", line 13, in update_projects
    ProjectStatusNotification(self.config, self.integration_status, new_integration_status, self.notification).show_notifications()
  File "/usr/local/lib/python2.7/dist-packages/buildnotifylib/project_status_notification.py", line 21, in show_notifications
    self.timed_project_filter.filter(map(lambda server: server.url, self.current_integration_status.unavailable_servers())), "Connectivity issues")
  File "/usr/local/lib/python2.7/dist-packages/buildnotifylib/project_status_notification.py", line 27, in show_notification_msg
    self.notification.show_message(message, "\n".join(builds))
  File "/usr/local/lib/python2.7/dist-packages/buildnotifylib/notifications.py", line 22, in show_message
    self.widget.showMessage(title, text, QtGui.QSystemTrayIcon.Information, 3000)
AttributeError: 'module' object has no attribute 'QSystemTrayIcon'
Aborted (core dumped)
```

The same happens if I disconnect from the network.

If there's a "Temporary failure in name resolution", buildnotify should display the grey "connection problem" icon, not abort with a coredump.

**Comment by anaynayak** [comment]
@Bu11etmagnet  this should now be fixed in v1.0.1 . The changes were done a bit earlier but sadly weren't pushed to PyPI.
